name: SoftBan
version: ${version}
main: dev.softban.SoftBanPlugin
api-version: '1.21.11'
depend:
  - ProtocolLib
authors:
  - fruit
description: Soft ban players by silently withholding outbound packets.
permissions:
  softban.command.softban:
    default: op
  softban.command.softbanip:
    default: op
  softban.command.softbanlist:
    default: op
  softban.command.softpardon:
    default: op
  softban.command.softpardonip:
    default: op
  softban.command.*:
    default: op
    children:
      softban.command.softban: true
      softban.command.softbanip: true
      softban.command.softbanlist: true
      softban.command.softpardon: true
      softban.command.softpardonip: true
